### ISSUE TITLE
Can you please update the tailwind peer dependency version

### ISSUE THREAD

**Issue by amit-jerno** [huygn/tailwind-unit-replace#1]

**Comment by huygn** [comment]
What peer version do you need to include? I'm not sure if this work with v3 because I haven't tried it yet.

**Comment by stevengunneweg** [comment]
I've tested this with my project and everything still seems to work properly with TW 3.3.1. I haven't verified every setting but at least I haven't found any issues. 
It would be great to have updated peer dependencies
