### ISSUE TITLE
Input, textarea select doesn't use the replaced unit sizing

### ISSUE THREAD

**Issue by DarkEye123** [huygn/tailwind-unit-replace#3]
The solution seems to be working out of the box for the majority of our components, but for some reason, inputs are not transformed as expected See the picture 
![image](https://github.com/huygn/tailwind-unit-replace/assets/5730144/eb08ea04-1594-49fb-8db3-c3ab3fe93d8a)

Applies for line-height, font-size etc

For some reason, input still uses `rem` sizing and not the converted one.

**Comment by huygn** [comment]
styles provided by plugins are not replace-able as they're are not placed inside the `theme` object. In your case I assume those are provided by `tailwind-forms`: https://github.com/tailwindlabs/tailwindcss-forms/blob/master/src/index.js#L51. So your best chance is to override them yourself, or write a custom postcss plugin to replace every css rules.
